name: 'demo_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'demo_dbt_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo_dbt_project:
    +materialized: table
